name: Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      # TODO: Uncomment this when we have fixed the ability to run the
      # integration tests on the github actions runner.
      # - name: Setup Ko
      #   uses: ko-build/setup-ko@v0.9

      # TODO: Uncomment this when we have fixed the ability to run the
      # integration tests on the github actions runner.
      # - name: Set up Docker
      #   uses: docker/setup-docker-action@v4

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: task test

      # TODO: Uncomment this when we have fixed the ability to run the
      # integration tests on the github actions runner.
      # - name: Test
      #   run: task test-integration